#!/usr/bin/env bash

function main {
  while true; do
    if [[ -f /tmp/done ]]; then
      break
    fi
    date
    sleep 1
  done

  if [[ "$(id -u -n)" != "ubuntu" ]]; then
    exec ssh -A -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@localhost "$BASH_SOURCE" "$@"
    return $?
  fi

  if [[ "$(id -u -n)" != "ubuntu" ]]; then
    echo "ERROR: failure to become ubuntu" 1>&2
    return 1
  fi

  if [[ ! -d .git ]]; then
    ssh -o StrictHostKeyChecking=no github.com true 2>/dev/null || true

    git clone git@github.com:imma/ubuntu
    mv ubuntu/.git .
    rm -rf ubuntu
  fi

  git fetch
  git reset --hard
  git pull

  mkdir -p .ssh
  if ssh -o Include=meh 2>&1 | grep -q 'Bad'; then
    cat .ssh/config.template
  else
    perl -pe 's{^#Include}{Include}' .ssh/config.template
  fi > .ssh/config
  chmod 600 .ssh/config

  mkdir -p .gnupg
  chmod 0700 .gnupg
  touch .gnupg/gpg.conf
  chmod 0600 .gnupg/gpg.conf

  sudo ln -nfs home /Users

  set +x
  script/setup
  make cache
  source .bash_profile

  sudo yum upgrade -y
	sudo yum install -y gcc-c++ gcc diffutils # pkgsrc
	sudo yum install -y zlib-devel # netdata
	sudo yum install -y readline-devel # ruby
	sudo yum install -y unzip nc # everyone
  (cd work/base && block bootstrap)
  set -x

  for a in {1..5}; do git clean -ffd || true; done
} 

main "$@"
