#!/usr/bin/env bash

function main {
  while true; do
    if [[ -f /tmp/done ]]; then
      break
    fi
    date
    sleep 1
  done

  ssh -o StrictHostKeyChecking=no github.com true 2>/dev/null || true

  git clone git@github.com:imma/ubuntu
  mv ubuntu/.git .
  rm -rf ubuntu
  git reset --hard
  git pull

  script/setup
  make cache
  source .bash_profile
  for a in {1..5}; do git clean -ffd || true; done
} 

main "$@"
